<?php require_once('include/links.php'); ?>
<?php require_once('include/header.php'); ?>
<?php require_once('welcome.php'); ?>
<?php require_once('about.php'); ?>
<?php require_once('service.php'); ?>
<?php require_once('work.php'); ?>
<?php require_once('stat.php'); ?>
<?php require_once('testimonial.php'); ?>
<?php require_once('contact.php'); ?>
<?php require_once('include/footer.php'); ?>